#! /bin/sh
#!/usr/bin/bash

## General ---------------------------------------------------#

wal -i ~/Pictures
wal -R
generate-theme.sh # generate google chrome theme

# source Pywal colors.
. "${HOME}/.cache/wal/colors.sh"

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

## Configurations --------------------------------------------#

## 8 workspaces
bspc monitor -d '' '' '' '' '' '' '' ''

## Apply bspwm configurations
bspc config border_width 2
bspc config window_gap 15
bspc config split_ratio 0.52

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

bspc rule -a alacritty-float state=floating follow=on focus=on
bspc rule -a htop-float state=floating follow=on focus=on

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 sxhkd dunst ncmpcpp ksuperkey greenclip xfce4-power-manager

# Fix cursor
xsetroot -cursor_name left_ptr
# Set keyboard layout
setxkbmap -layout us,ara -option 'grp:alt_shift_toggle'
# Set super key for menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# lxsession
exec lxsession -s bspwm -e bspwm &

# Power manager
xfce4-power-manager &

# Lauch keybindings daemon
sxhkd &
# Polybar
$HOME/.config/polybar/launch
# Picom
$HOME/.config/picom/launch
# Dunst
$HOME/.config/dunst/launch
# Syncthing
syncthing &
# Greenclip
greenclip daemon
